### ISSUE TITLE
[Question] npc linking

### ISSUE THREAD

**Issue by AggerTV** [Blackixx/BossShopPro#100]
In minecraft 1.16.5, how do I make it so that players don't have access to e.g /shop shop1, but they can click an npc linked to shop1 instead? I know there was this addon, but it only supported minecraft up to 1.12.2

**Comment by Tanerx** [comment]
Change shop name noone can guess.

**Comment by Blackixx** [comment]
Simply do not give players permissions to the shop. The npcs themselves could simply trigger the console command of BSP to open the shop of a certain player instead of making the player execute the command by themselves.
E.g.:
- Players have no permissions for shop
- NPCs trigger the console command "shop open <shopname> %player%"
